name: diablo
description: "A Mt Diablo project"
# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensure compatibility with Flutter's latest stable version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.jpg
    - assets/icons/background_icon_optimized.jpg